name: innerscape
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  sqflite: ^2.4.2+1
  path: ^1.9.1
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  groq_sdk: ^1.0.2
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  shared_preferences: ^2.3.5
  pdf: ^3.11.2
  printing: ^5.14.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  encrypt: ^5.0.3
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/design/
    - .env
  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Variable.ttf
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
        - asset: assets/fonts/InstrumentSerif-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/design/logo_landscape.jpg"
  remove_alpha_ios: true
